### PR TITLE
Make compatible with kitnic.it

### PR DESCRIPTION
**Pull request by kasbah**
Hey, thanks very much for doing the work on this project. I have read your posts on Hackaday.io with much interest. I am thinking of building one of these and have used your comments on Hackaday and my [1-click BOM browser extension](https://1clickbom.com) and some more experimental tools I am working on to try and figure out [the BOM](https://github.com/kitnic-forks/ice40_eink_controller/blob/master/hardware/1-click-bom.tsv). I am still missing parts for:

- All the inductors (L1-L4) as I couldn't figure out the footprint. 
- The SPI flash (U5), what speed, what size etc. 

Do you have any manufacturer or retailer part numbers for these? Could you also go over my part selection and see if I have messed up somewhere? I am not really sure on the SRAM (U7) choice for instance. 

With the BOM sorted out this project could go on my site: [kitnic.it](https://kitnic.it) where other people could then more easily buy the right parts to re-build it. Here is [a preview of what that would look like](http://add-ice40-eink.preview.kitnic.it/boards/github.com/kitnic-forks/ice40_eink_controller/). Would you be interested in having it put up? Can I use your work under an open source license?

### CODE REVIEW

**Comment by julbouln** [comment]
Hi @kasbah,
Your project looks awesome ! 
To answer your questions, here is the missing parts I used :
SPI flash : SST25VF010A Mbit
L1: 4.7uH CIG22L4R7MNE
L2-L4: 2.2uH CIG22L2R2MNE

After reading the BOM, I can see some issues :
U2 and U3 FPGA power supplies are not the same, U3 is LM3671MF-3.3 (3.3V) and U2 is LM3671MF-1.2 (1.2V)
I have not checked the capitors you choosed, but some have voltage requirements:
C12,C23 must be rated min 16V
C11,C22 must be rated min 25V
The others could be rated 6.3V

For the memory, I used https://www.olimex.com/Products/Components/IC/K6R4016V1D-TC10/, the main requirement with the pinout is the refresh rate, 
10ns is really needed, so as I think IS61WV2561 should be a good replacement.

Of course it is an open source project, I did not indicate any license see that as "I don't care" or public domain, so you can use it as you wish ! Anyway, I would be glad to see it in your project :)

**Comment by julbouln** [comment]
It seems good !

**Comment by kasbah** [comment]
Cool stuff! I will put it up on Kitnic but keep working on the BOM. You also get some free PCB vouchers for putting your project up, do you have a private way to send you that (email, IRC)? 

By the way, you don't have any spare PCBs of _this_ project do you? I think I will really want to make one once the BOM is sorted. If you don't have any I should put an order in soon.

**Comment by kasbah** [comment]
[It's UP!](https://kitnic.it/boards/github.com/julbouln/ice40_eink_controller/) (The drills in the rendering will be sorted once https://github.com/mcous/gerber-parser/pull/17 is merged and released).

**Comment by julbouln** [comment]
Yes it is a good idea to test it ! I have two spare PCBs left, maybe you can reach me on hackaday.io ?
Oops I think U2 and U3 are still the same

**Comment by kasbah** [comment]
Yes, I was actually updating the BOM independently before reading your feedback. Will fix it soon and send another PR. I sent you a message on HaD with the voucher code.
 
Is the [ifusb](https://github.com/julbouln/ifusb) required for getting the board running? Might try my BOM builder on that as well.

**Comment by julbouln** [comment]
ifusb is not required, but it will be a lot easier to have it to test (programming the fpga, and interfacing the screen)

**Pull request merged**
